all: run
# XXXX: for global scipy
run:
	PYTHONPATH=/usr/lib/python2.7/dist-packages \
	python ./track.py --gui


# install:
# 	sudo apt-get install python-scipy

# install-hack:
# 	cp /usr/lib/pymodules/python2.7/cv* \
# 	$(VIRTUAL_ENV)/lib/python2.7/site-packages/
# 	python -c 'import cv, cv2'
